
sudo: required

services:
    - docker

before_install:
    - docker pull victorhcm/opencv-qt5
    - docker run victorhcm/opencv-qt5 /bin/bash "cd /root; git clone https://github.com/victorhcm/mini-cmake-qt; cd mini-cmake-qt; mkdir build; cd build; cmake ..; make; ls"

# after_success:
#     - 
